### ISSUE TITLE
Low disk on ws-ci-runner bastion

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-workstation-ci#43]
There was an alert for less than 20% disk space on the CI bastion server. I logged in and saw:
```
root@ws-ci-bastion:/var/lib# du -hs * | sort -hr | head
2.0G	ws-ci-runner
```

All of these seem like checkouts of the workstation repo that should be safe to eventually clean up after the test run?

In the meantime I ran `apt clean` to get 400M back.

**Comment by mig5** [comment]
Thanks, yeah, I forgot to remove the workstation repo that gets cloned as part of the webhook. I don't think we even need it after we fire off the call to the `run.py`. It is only used to determine the Qubes version to run the CI against.

Thanks for the help!
