### ISSUE TITLE
Maintenance of CI code and procedure for releasing changes

### ISSUE THREAD

**Issue by mig5** [freedomofpress/securedrop-workstation-ci#56]
## Preamble

The infra team wrote the original CI implementation for SDW CI, but now that it is being used in earnest by the SD team, it makes sense for the SD team to want to make changes and perhaps gradually assume maintainer responsibility of the project.

Making changes to the code is already something SD team can do via this repo, PRs etc. But getting those changes out onto the SDW CI infrastructure still involves infra team.

Discussions are under way regarding how to handle this. This is my proposal to resolve the issue, hopefully without requiring a million meetings about it.

## Making changes to the code

As mentioned - SD team can already start changing the code and handling peer review between their team right here - they have the appropriate Github permissions for this repo.

## Applying the changes to infrastructure - CI-level code

Right now, this CI repo's changes are 'pulled' onto the bastion by applying an Ansible playbook by the infra team. The SD team can't do this as they don't have the required permissions for reading certain files (this *could* be changed but I would argue is needlessly unpicking something that could be solved a different way).

Now, the bastion already has a webhook that receives push events for the `securedrop-workstation` repo itself (that's what triggers the whole CI process).

Proposed solution for updating the CI files on the bastion: I simply add the *same* webhook address/secret to this `securedrop-workstation-ci` repository's settings. 

Then, in the `webhook.py` on the bastion (managed in ansible), I add a simple python condition that checks 'was this push event from `securedrop-workstation` repo?' - if so, perform the CI as normal. If the event was from `securedrop-workstation-ci` repo, simply subprocess a `git pull origin main` of the CI code on the bastion.

In short, the webhook then provides two separate functions: either triggering CI or pulling the CI codebase, depending on which repo triggered the webhook.

In doing so, you now have an automated deployment of changes to the CI codebase, without needing SD or infra team to do anything else other than merge a PR. This is also better than a cron (my previous suggestion), as it is more 'controlled' - changes to the CI code only arrive on the bastion when we purposefully merge those changes - and it is also more 'visible' than a cron.

## Applying changes to the infrastructure - Webhook logic itself

For changes to the actual webhook.py itself, I propose that it remain in the infrastructure repo as part of the Ansible playbook, and is something only infra team apply. The main reasons for this are:

1) Changes to the webhook necessitate a reload of the systemd service (as a privileged user). It's not something that can be handled in this CI repo itself (or by the webhook processing its events itself).

2) Changes to the webhook could contain bugs that impact uptime of the service itself. 'Is it up and running' is already akin to an infra-team mindset/responsibility e.g something we can monitor and respond to via Icinga - and the infra team already implicitly is involved in keeping the bastion and the ESXi itself running and patched, etc. 

I think it therefore makes sense for infra team to, at the very least, be *aware* of a change occurring to *that* part of the codebase, so we have the context. In that case, I propose that infra team continue to be the party responsible for applying changes to the webhook/vhost etc. The SD team can always ping the infra team to ask for such a 'deployment', but any such changes would already be arriving as a PR to the infra repo anyway, meaning infra team would already be aware of such a request.

To my mind, it all kind of solves itself by merely adding the webhook to this repo to handle automated deployments of the CI code itself. Infra team need not be a gatekeeper then, and the SD team can quickly start to evolve the codebase.

This may all change again if we were to switch to GHA but we can talk about that later.
___

I am tabling this for discussion at our next meeting with SD and Infra about maintenance of the CI code. Having said that, I personally see no reason to wait, and think I could easily make the webhook change per my proposal, thereby immediately unblocking the SD team for releasing PRs such as https://github.com/freedomofpress/securedrop-workstation-ci/pull/55 and others, without needing infra team for such things. If we want to press ahead, why not discuss it async here and I can just make it happen.

**Comment by soleilera** [comment]
> In short, the webhook then provides two separate functions: either triggering CI or pulling the CI codebase, depending on which repo triggered the webhook.
> 
> In doing so, you now have an automated deployment of changes to the CI codebase, without needing SD or infra team to do anything else other than merge a PR. This is also better than a cron (my previous suggestion), as it is more 'controlled' - changes to the CI code only arrive on the bastion when we purposefully merge those changes - and it is also more 'visible' than a cron.
> 

this is a cool idea. :+1: from me on doing it before our May 1st meeting and if we also get a :+1: from an SD team rep

**Comment by soleilera** [comment]
but also... it's fine if there isn't time to do it right away and we just deploy whatever the sd team merges in the meantime

**Comment by eloquence** [comment]
Thanks Mig, and +1 to @soleilera, makes sense to me. For PRs like #55, in any event, per discussion at infra team meeting today, it's already understood that  @legoktm and other SecureDrop maintainers can peer review and merge each other's changes in this repo (and then tag infra for deploy til we have automation).

So can you, but you shouldn't feel like you're obligated to review/merge such changes, so feel free to unassign yourself from PRs that don't need infra involvement. :)

**Comment by legoktm** [comment]
Thanks for getting this started Mig. We discussed this a bit in the SD team meeting today and overall +1 on it, no need to wait until May.

I personally think that leaving webhook.py where it is in the infra repo has a nice side feature of making sure merging in this repo can't break deploys since we'll still be able to push out a revert.  

The one ask was to make it clear in an architecture document which parts live in this repo and which are in the infra repository - I'm happy to take that on.
